# https://blog.csanchez.org/2020/10/07/building-docker-images-with-kaniko-pushing-to-amazon-elastic-container-registry-ecr/
FROM gcr.io/kaniko-project/executor:debug

COPY config.json /kaniko/.docker/config.json